
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadGimnasio
{

using System;
    using System.Collections.Generic;
    
public partial class Horario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario()
    {

        this.Asistencia = new HashSet<Asistencia>();

        this.Reserva = new HashSet<Reserva>();

    }


    public int id { get; set; }

    public string dia { get; set; }

    public Nullable<System.TimeSpan> hora_inicio { get; set; }

    public Nullable<System.TimeSpan> hora_fin { get; set; }

    public Nullable<int> id_servicio { get; set; }

    public Nullable<int> id_entrenador { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asistencia> Asistencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

    public virtual Entrenador Entrenador { get; set; }

    public virtual Servicio Servicio { get; set; }

}

}
