//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_membresia { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public decimal monto_pagado { get; set; }
        public string metodo_pago { get; set; }
        public System.DateTime fecha_transaccion { get; set; }
        public string estado_inscripcion { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Membresia Membresia { get; set; }
    }
}
