

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadGimnasio
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class GimnasioEntities : DbContext
{
    public GimnasioEntities()
        : base("name=GimnasioEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Asistencia> Asistencia { get; set; }

    public virtual DbSet<Entrenador> Entrenador { get; set; }

    public virtual DbSet<Horario> Horario { get; set; }

    public virtual DbSet<Membresia> Membresia { get; set; }

    public virtual DbSet<Pago> Pago { get; set; }

    public virtual DbSet<Reserva> Reserva { get; set; }

    public virtual DbSet<Servicio> Servicio { get; set; }

    public virtual DbSet<UsuarioSistema> UsuarioSistema { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }


    public virtual ObjectResult<spUsuarioListar_Result> spUsuarioListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUsuarioListar_Result>("spUsuarioListar", parametroParameter);
    }


    public virtual ObjectResult<spEntrenadorListar_Result> spEntrenadorListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEntrenadorListar_Result>("spEntrenadorListar", parametroParameter);
    }


    public virtual ObjectResult<spUsuarioListar1_Result> spUsuarioListar1(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUsuarioListar1_Result>("spUsuarioListar1", parametroParameter);
    }


    public virtual ObjectResult<spAsistenciaListar_Result> spAsistenciaListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAsistenciaListar_Result>("spAsistenciaListar", parametroParameter);
    }


    public virtual ObjectResult<spHorarioListar_Result> spHorarioListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spHorarioListar_Result>("spHorarioListar", parametroParameter);
    }


    public virtual ObjectResult<spMembresiaListar_Result> spMembresiaListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMembresiaListar_Result>("spMembresiaListar", parametroParameter);
    }


    public virtual ObjectResult<spPagoListar_Result> spPagoListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPagoListar_Result>("spPagoListar", parametroParameter);
    }


    public virtual ObjectResult<spReservaListar_Result> spReservaListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReservaListar_Result>("spReservaListar", parametroParameter);
    }


    public virtual ObjectResult<spServicioListar_Result> spServicioListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spServicioListar_Result>("spServicioListar", parametroParameter);
    }

}

}

