//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadGimnasio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_horarioclase { get; set; }
        public System.DateTime fecha_reserva { get; set; }
        public bool asistio { get; set; }
        public string estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual HorarioClase HorarioClase { get; set; }
    }
}
